
services:
  - type: web
    name: yolo-ml-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:9090 --workers 1 --timeout 300 _wsgi:app
    envVars:
      - key: PORT
        value: 9090
